import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const SCRIPT_DIR = fileURLToPath(new URL('../scripts/', import.meta.url));

function createWorkspace(t, files) {
  const workspace = fs.mkdtempSync(path.join(os.tmpdir(), 'context-engineering-template-'));
  t.after(() => fs.rmSync(workspace, { recursive: true, force: true }));

  for (const [file, content] of Object.entries(files)) {
    const full = path.join(workspace, ...file.split('/'));
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content, 'utf8');
  }

  return workspace;
}

function runScript(workspace, script, args = []) {
  return spawnSync(process.execPath, [path.join(SCRIPT_DIR, script), ...args], {
    cwd: workspace,
    encoding: 'utf8'
  });
}

function readFile(workspace, file) {
  return fs.readFileSync(path.join(workspace, ...file.split('/')), 'utf8');
}

test('docs-sync normalizes document map paths and excludes session logs', t => {
  const workspace = createWorkspace(t, {
    'docs/index.md': `---\ntype: docs_index\nstatus: active\npriority: p1\nupdated: 2026-05-24\ncontext_policy: on_demand\nowner: project\n---\n\n# Documentation Index\n`,
    'docs/accessibility.md': `---\ntype: accessibility_policy\nstatus: active\nupdated: 2026-05-24\ncontext_policy: retrieve_when_planning\nowner: project\n---\n\n# Accessibility Policy\n`,
    'docs/memory/current.md': `---\ntype: working_memory\nstatus: active\nupdated: 2026-05-24\ncontext_policy: always_retrievable\nowner: project\n---\n\n# Current Project Memory\n`,
    'docs/memory/sessions/YYYY-MM-DD.md': `---\ntype: session_log\nstatus: archive\nupdated: 2026-05-24\ncontext_policy: historical\nowner: project\n---\n\n# Session Log: YYYY-MM-DD\n`,
    'docs/adr/0000-template.md': `---\ntype: adr\nstatus: template\nupdated: 2026-05-24\ncontext_policy: on_demand\nowner: project\n---\n\n# ADR-0000: Decision Title\n`,
    'docs/adr/0001-example.md': `---\ntype: adr\nstatus: proposed\nupdated: 2026-05-24\ncontext_policy: on_demand\nowner: project\n---\n\n# ADR-0001: Example Decision\n`
  });

  const result = runScript(workspace, 'docs-sync.mjs');
  assert.equal(result.status, 0, result.stderr || result.stdout);

  const index = readFile(workspace, 'docs/index.md');
  const decisions = readFile(workspace, 'docs/decisions.md');

  assert.match(index, /`docs\/accessibility\.md`/);
  assert.doesNotMatch(index, /docs\\accessibility\.md/);
  assert.doesNotMatch(index, /docs\/memory\/sessions\//);
  assert.match(decisions, /\| `0000` \| template \| ADR-0000: Decision Title \|/);
  assert.match(decisions, /\| `0001` \| proposed \| ADR-0001: Example Decision \|/);
});

test('docs-completed-regen preserves the updated date when content is unchanged', t => {
  const completed = `---\ntype: task_archive_index\nstatus: archive\npriority: p3\nupdated: 2024-01-02\ncontext_policy: on_demand\nowner: project\n---\n\n# Completed Task Index\n\n<!-- AUTO-GENERATED by scripts/docs-completed-regen.mjs -->\n\nNo completed task markers found yet.\n`;
  const workspace = createWorkspace(t, {
    'docs/tasks/completed.md': completed,
    'docs/memory/sessions/.gitkeep': ''
  });

  const result = runScript(workspace, 'docs-completed-regen.mjs');
  assert.equal(result.status, 0, result.stderr || result.stdout);
  assert.match(result.stdout, /unchanged/);
  assert.equal(readFile(workspace, 'docs/tasks/completed.md'), completed);
});

test('docs-guard-adr-status allows the template ADR and validates superseded references', t => {
  const workspace = createWorkspace(t, {
    'docs/adr/0000-template.md': `---\ntype: adr\nstatus: template\nupdated: 2026-05-24\ncontext_policy: on_demand\nowner: project\n---\n\n# ADR-0000: Decision Title\n`,
    'docs/adr/0001-replaced-thing.md': `---\ntype: adr\nstatus: superseded\nupdated: 2026-05-24\ncontext_policy: on_demand\nowner: project\n---\n\n# ADR-0001: Replaced Thing\n\nSuperseded by ADR-0002.\n`,
    'docs/adr/0002-better-thing.md': `---\ntype: adr\nstatus: accepted\nupdated: 2026-05-24\ncontext_policy: on_demand\nowner: project\n---\n\n# ADR-0002: Better Thing\n\n## Decision\n\nUse the better thing.\n\n## Consequences\n\nIt is better.\n`
  });

  const result = runScript(workspace, 'docs-guard-adr-status.mjs');
  assert.equal(result.status, 0, result.stderr || result.stdout);
  assert.match(result.stdout, /adr status ok/);
});

test('docs-guard-adr-status fails superseded ADRs that do not name a replacement', t => {
  const workspace = createWorkspace(t, {
    'docs/adr/0000-template.md': `---\ntype: adr\nstatus: template\nupdated: 2026-05-24\ncontext_policy: on_demand\nowner: project\n---\n\n# ADR-0000: Decision Title\n`,
    'docs/adr/0001-replaced-thing.md': `---\ntype: adr\nstatus: superseded\nupdated: 2026-05-24\ncontext_policy: on_demand\nowner: project\n---\n\n# ADR-0001: Replaced Thing\n\nThis decision is no longer current.\n`
  });

  const result = runScript(workspace, 'docs-guard-adr-status.mjs');
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /ADR SUPERSEDED FAIL/);
});

test('docs-guard-secrets passes clean documentation files', t => {
  const workspace = createWorkspace(t, {
    'README.md': '# Clean Repo\n',
    'CLAUDE.md': '# Bootstrap\n',
    'docs/project.md': `---\ntype: project_overview\nstatus: active\nupdated: 2026-06-04\ncontext_policy: always_retrievable\nowner: project\n---\n\n# Project Overview\n\nNo secrets here.\n`
  });

  const result = runScript(workspace, 'docs-guard-secrets.mjs');
  assert.equal(result.status, 0, result.stderr || result.stdout);
  assert.match(result.stdout, /secret scan ok/);
});

test('docs-guard-secrets fails when a high-confidence token pattern is present', t => {
  const workspace = createWorkspace(t, {
    'README.md': 'Leaked key AKIA1234567890ABCDEF should fail.\n'
  });

  const result = runScript(workspace, 'docs-guard-secrets.mjs');
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /SECRET FAIL README\.md: detected AWS access key/);
});

test('docs-new-adr creates the next proposed ADR from a title', t => {
  const workspace = createWorkspace(t, {
    'docs/adr/0000-template.md': `---\ntype: adr\nstatus: template\nupdated: 2026-05-24\ncontext_policy: on_demand\nowner: project\n---\n\n# ADR-0000: Decision Title\n`,
    'docs/adr/0001-existing-decision.md': `---\ntype: adr\nstatus: proposed\nupdated: 2026-05-24\ncontext_policy: on_demand\nowner: project\n---\n\n# ADR-0001: Existing Decision\n`
  });

  const result = runScript(workspace, 'docs-new-adr.mjs', ['Security Boundary Review']);
  assert.equal(result.status, 0, result.stderr || result.stdout);

  const file = 'docs/adr/0002-security-boundary-review.md';
  const content = readFile(workspace, file);
  assert.match(result.stdout, new RegExp(`created ${file}`));
  assert.match(content, /status: proposed/);
  assert.match(content, /# ADR-0002: Security Boundary Review/);
  assert.match(content, /## Security Review/);
  assert.match(content, /## Resource Impact/);
});

test('docs-new-adr requires a title', t => {
  const workspace = createWorkspace(t, {
    'docs/adr/0000-template.md': ''
  });

  const result = runScript(workspace, 'docs-new-adr.mjs');
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /Usage: npm run docs:new-adr/);
});

test('team-register and team-whoami set a local identity', t => {
  const workspace = createWorkspace(t, {});

  const register = runScript(workspace, 'team-register.mjs', ['shawn', 'Shawn', 'maintainer']);
  assert.equal(register.status, 0, register.stderr || register.stdout);
  assert.match(register.stdout, /registered shawn/);

  const whoami = runScript(workspace, 'team-whoami.mjs', ['shawn']);
  assert.equal(whoami.status, 0, whoami.stderr || whoami.stdout);
  assert.match(whoami.stdout, /current identity: shawn/);

  const members = readFile(workspace, 'docs/team/members.md');
  const identity = JSON.parse(readFile(workspace, '.context/identity.json'));
  assert.match(members, /\| `shawn` \| Shawn \| maintainer \| true \|/);
  assert.equal(identity.member_id, 'shawn');
});

test('team-guard validates active task owners against registered members', t => {
  const workspace = createWorkspace(t, {
    'docs/team/members.md': `---\ntype: team_registry\nstatus: active\nupdated: 2026-06-04\ncontext_policy: retrieve_when_planning\nowner: project\n---\n\n# Team Members\n\n| ID | Display name | Role | Active | Notes |\n|---|---|---|---|---|\n| \`shawn\` | Shawn | maintainer | true | |\n`,
    'docs/tasks/active.md': `---\ntype: task_index\nstatus: active\nupdated: 2026-06-04\ncontext_policy: always_retrievable\nowner: project\n---\n\n# Active Tasks\n\n## Active Queue\n\n### TASK.001 - Example\n\n- Status: doing\n- Owner: shawn\n`
  });

  const result = runScript(workspace, 'team-guard.mjs');
  assert.equal(result.status, 0, result.stderr || result.stdout);
  assert.match(result.stdout, /team guard ok/);
});

test('team-guard fails when an active task owner is not registered', t => {
  const workspace = createWorkspace(t, {
    'docs/team/members.md': `---\ntype: team_registry\nstatus: active\nupdated: 2026-06-04\ncontext_policy: retrieve_when_planning\nowner: project\n---\n\n# Team Members\n\n| ID | Display name | Role | Active | Notes |\n|---|---|---|---|---|\n| \`shawn\` | Shawn | maintainer | true | |\n`,
    'docs/tasks/active.md': `---\ntype: task_index\nstatus: active\nupdated: 2026-06-04\ncontext_policy: always_retrievable\nowner: project\n---\n\n# Active Tasks\n\n## Active Queue\n\n### TASK.001 - Example\n\n- Status: doing\n- Owner: alice\n`
  });

  const result = runScript(workspace, 'team-guard.mjs');
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /owner alice is not registered/);
});

test('docs-new-session requires identity and creates a member-specific session log', t => {
  const workspace = createWorkspace(t, {
    'docs/team/members.md': `---\ntype: team_registry\nstatus: active\nupdated: 2026-06-04\ncontext_policy: retrieve_when_planning\nowner: project\n---\n\n# Team Members\n\n| ID | Display name | Role | Active | Notes |\n|---|---|---|---|---|\n| \`shawn\` | Shawn | maintainer | true | |\n`,
    'docs/memory/sessions/YYYY-MM-DD.md': `---\ntype: session_log\nstatus: archive\nupdated: YYYY-MM-DD\ncontext_policy: historical\nowner: project\n---\n\n# Session Log: YYYY-MM-DD\n`
  });

  const first = runScript(workspace, 'docs-new-session.mjs');
  assert.notEqual(first.status, 0);
  assert.match(first.stderr, /TEAM IDENTITY FAIL/);

  const whoami = runScript(workspace, 'team-whoami.mjs', ['shawn']);
  assert.equal(whoami.status, 0, whoami.stderr || whoami.stdout);

  const second = runScript(workspace, 'docs-new-session.mjs');
  assert.equal(second.status, 0, second.stderr || second.stdout);

  const match = second.stdout.match(/created (docs\/memory\/sessions\/\d{4}-\d{2}-\d{2}-shawn\.md)/);
  assert.ok(match, second.stdout);
  const content = readFile(workspace, match[1]);
  assert.match(content, /owner: shawn/);
  assert.match(content, /# Session Log: \d{4}-\d{2}-\d{2} - Shawn/);
});
