#include "generator_registry.hpp"
#include "generator_support.hpp"
#include "judge/case_generator.hpp"
#include <algorithm>
#include <random>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>
namespace judge::generators{namespace{
GeneratedCase arrayCase(std::mt19937_64& r,int q){if(q<7)throw std::runtime_error("A61 limit");std::vector<std::vector<int>> v{{1,2,3,4,5}};std::ostringstream in,out;in<<"5 "<<q<<"\n1 2 3 4 5\n";in<<"update 0 2 10\n";v.push_back({1,2,10,4,5});appendLine(out,1);in<<"update 0 0 9\n";v.push_back({9,2,3,4,5});appendLine(out,2);in<<"get 0 2\n";appendLine(out,3);in<<"get 1 0\n";appendLine(out,1);in<<"get 2 0\n";appendLine(out,9);in<<"sum 1 0 4\n";appendLine(out,22);in<<"versions\n";appendLine(out,3);for(int e=7;e<q;++e){int ver=randomInt(r,0,static_cast<int>(v.size())-1),i=randomInt(r,0,4);if(randomInt(r,0,1)){int x=randomInt(r,-20,20);in<<"update "<<ver<<' '<<i<<' '<<x<<'\n';auto n=v[ver];n[i]=x;v.push_back(n);appendLine(out,static_cast<int>(v.size())-1);}else{in<<"get "<<ver<<' '<<i<<'\n';appendLine(out,v[ver][i]);}}return{in.str(),out.str()};}
bool starts(const std::string&a,const std::string&b){return a.size()>=b.size()&&a.compare(0,b.size(),b)==0;}GeneratedCase trieCase(std::mt19937_64&r,int q){if(q<7)throw std::runtime_error("A62 limit");std::vector<std::vector<std::string>>v(1);std::ostringstream in,out;in<<q<<'\n';auto add=[&](int ver,std::string w){in<<"insert "<<ver<<' '<<w<<'\n';auto n=v[ver];n.push_back(w);v.push_back(n);appendLine(out,static_cast<int>(v.size())-1);};add(0,"app");add(1,"apple");add(0,"apt");in<<"contains 2 apple\n";appendLine(out,"true");in<<"contains 3 app\n";appendLine(out,"false");in<<"prefix_count 2 app\n";appendLine(out,2);in<<"versions\n";appendLine(out,4);std::vector<std::string>w={"a","app","bat","bar"};for(int e=7;e<q;++e){int ver=randomInt(r,0,static_cast<int>(v.size())-1);std::string x=w[randomInt(r,0,3)];if(randomInt(r,0,1))add(ver,x);else{in<<"prefix_count "<<ver<<' '<<x.substr(0,1)<<'\n';int c=0;for(auto&s:v[ver])if(starts(s,x.substr(0,1)))++c;appendLine(out,c);}}return{in.str(),out.str()};}
GeneratedCase lineCase(std::mt19937_64&r,int q){if(q<5)throw std::runtime_error("A63 limit");std::vector<std::pair<long long,long long>>v;std::ostringstream in,out;in<<q<<'\n';auto add=[&](int m,int b){in<<"add_line "<<m<<' '<<b<<'\n';v.push_back({m,b});};auto ask=[&](int x){in<<"query "<<x<<'\n';if(v.empty())appendLine(out,"EMPTY");else{long long a=1LL<<60;for(auto[m,b]:v)a=std::min(a,m*x+b);appendLine(out,static_cast<int>(a));}};ask(0);add(2,3);add(-1,10);ask(0);ask(10);for(int e=5;e<q;++e)if(randomInt(r,0,2)==0)add(randomInt(r,-10,10),randomInt(r,-20,20));else ask(randomInt(r,-30,30));return{in.str(),out.str()};}
struct I{int id,l,r;};GeneratedCase intervalCase(std::mt19937_64&r,int q){if(q<6)throw std::runtime_error("A64 limit");std::vector<I>v;std::ostringstream in,out;in<<q<<'\n';auto add=[&](int id,int l,int h){in<<"add "<<id<<' '<<l<<' '<<h<<'\n';v.push_back({id,l,h});};auto stab=[&](int x){in<<"stab "<<x<<'\n';std::vector<int>ids;for(auto a:v)if(a.l<=x&&x<=a.r)ids.push_back(a.id);std::sort(ids.begin(),ids.end());if(ids.empty())appendLine(out,"EMPTY");else{for(size_t i=0;i<ids.size();++i)out<<(i?" ":"")<<ids[i];out<<'\n';}};add(1,0,5);add(2,5,10);stab(5);in<<"remove 1\n";v.erase(v.begin());appendLine(out,"REMOVED");stab(5);in<<"count\n";appendLine(out,1);int id=3;for(int e=6;e<q;++e)if(randomInt(r,0,1)){int l=randomInt(r,-20,20),h=randomInt(r,l,25);add(id++,l,h);}else stab(randomInt(r,-20,20));return{in.str(),out.str()};}
}void registerSpecializedGenerators(CaseGeneratorRegistry&x){x.emplace("A61-persistent-array",arrayCase);x.emplace("A62-persistent-trie",trieCase);x.emplace("A63-li-chao-tree",lineCase);x.emplace("A64-dynamic-interval-tree",intervalCase);}}
