#include "generator_registry.hpp"
#include "generator_support.hpp"
#include "judge/case_generator.hpp"
#include <algorithm>
#include <random>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>
namespace judge::generators { namespace {
bool startsWith(const std::string& value,const std::string& prefix){return value.size()>=prefix.size()&&value.compare(0,prefix.size(),prefix)==0;}
void appendWords(std::ostringstream& output,std::vector<std::string> words){std::sort(words.begin(),words.end());words.erase(std::unique(words.begin(),words.end()),words.end());if(words.empty()){appendLine(output,"EMPTY");return;}for(std::size_t i=0;i<words.size();++i)output<<(i?" ":"")<<words[i];output<<'\n';}
const std::vector<std::string> kWords={"a","app","apple","apt","bat","bar","bark","cat","car","cart","dog","dot","he","her","hers"};
GeneratedCase generateTrie(std::mt19937_64& random,int operations){if(operations<8)throw std::runtime_error("A55-trie-multiset operation_limit too small");std::vector<std::string> words;std::ostringstream input,output;input<<operations<<'\n';auto insert=[&](std::string w){input<<"insert "<<w<<'\n';words.insert(std::upper_bound(words.begin(),words.end(),w),w);};auto erase=[&](std::string w){input<<"erase "<<w<<'\n';auto at=std::lower_bound(words.begin(),words.end(),w);if(at==words.end()||*at!=w)appendLine(output,"NOT_FOUND");else{words.erase(at);appendLine(output,"REMOVED");}};insert("app");insert("apple");insert("app");input<<"prefix_count app\n";appendLine(output,3);erase("app");input<<"count app\n";appendLine(output,1);input<<"autocomplete ap\n";appendLine(output,"app apple");input<<"size\n";appendLine(output,2);for(int e=8;e<operations;++e){std::string w=kWords[randomInt(random,0,static_cast<int>(kWords.size())-1)];int kind=randomInt(random,0,6);if(kind<=1)insert(w);else if(kind==2)erase(w);else if(kind==3){input<<"contains "<<w<<'\n';appendLine(output,std::binary_search(words.begin(),words.end(),w)?"true":"false");}else if(kind==4){input<<"count "<<w<<'\n';appendLine(output,static_cast<int>(std::upper_bound(words.begin(),words.end(),w)-std::lower_bound(words.begin(),words.end(),w)));}else if(kind==5){std::string p=w.substr(0,randomInt(random,1,static_cast<int>(w.size())));input<<"prefix_count "<<p<<'\n';int count=0;for(auto& value:words)if(startsWith(value,p))++count;appendLine(output,count);}else{std::string p=w.substr(0,1);input<<"autocomplete "<<p<<'\n';std::vector<std::string> result;for(auto& value:words)if(startsWith(value,p))result.push_back(value);appendWords(output,result);}}return{input.str(),output.str()};}
GeneratedCase generateRadix(std::mt19937_64& random,int operations){if(operations<8)throw std::runtime_error("A56-radix-tree-dictionary operation_limit too small");std::vector<std::string> words;std::ostringstream input,output;input<<operations<<'\n';auto insert=[&](std::string w){input<<"insert "<<w<<'\n';auto at=std::lower_bound(words.begin(),words.end(),w);if(at!=words.end()&&*at==w)appendLine(output,"DUPLICATE");else words.insert(at,w);};insert("test");insert("tester");insert("team");input<<"longest_prefix testing\n";appendLine(output,"test");input<<"prefix_count test\n";appendLine(output,2);input<<"insert test\n";appendLine(output,"DUPLICATE");input<<"words\n";appendLine(output,"team test tester");input<<"size\n";appendLine(output,3);for(int e=8;e<operations;++e){std::string w=kWords[randomInt(random,0,static_cast<int>(kWords.size())-1)];int kind=randomInt(random,0,5);if(kind<=1)insert(w);else if(kind==2){input<<"contains "<<w<<'\n';appendLine(output,std::binary_search(words.begin(),words.end(),w)?"true":"false");}else if(kind==3){input<<"prefix_count "<<w<<'\n';int count=0;for(auto& value:words)if(startsWith(value,w))++count;appendLine(output,count);}else if(kind==4){std::string text=w+"xyz",best;for(auto& value:words)if(startsWith(text,value)&&value.size()>best.size())best=value;input<<"longest_prefix "<<text<<'\n';appendLine(output,best.empty()?"NONE":best);}else{input<<"size\n";appendLine(output,static_cast<int>(words.size()));}}return{input.str(),output.str()};}
GeneratedCase generateXorTrie(std::mt19937_64& random,int operations){if(operations<8)throw std::runtime_error("A57-xor-trie-multiset operation_limit too small");std::vector<unsigned> values;std::ostringstream input,output;input<<operations<<'\n';auto insert=[&](unsigned x){input<<"insert "<<x<<'\n';values.push_back(x);};auto query=[&](std::string command,unsigned x){input<<command<<' '<<x<<'\n';if(values.empty()){appendLine(output,"EMPTY");return;}unsigned best=values[0]^x;for(unsigned value:values)best=command=="max_xor"?std::max(best,value^x):std::min(best,value^x);appendLine(output,static_cast<int>(best));};insert(5);insert(10);insert(5);query("max_xor",7);query("min_xor",7);input<<"erase_one 5\n";values.erase(std::find(values.begin(),values.end(),5));appendLine(output,"REMOVED");input<<"count 5\n";appendLine(output,1);input<<"size\n";appendLine(output,2);for(int e=8;e<operations;++e){unsigned x=static_cast<unsigned>(randomInt(random,0,127));int kind=randomInt(random,0,4);if(kind==0)insert(x);else if(kind==1){input<<"erase_one "<<x<<'\n';auto at=std::find(values.begin(),values.end(),x);if(at==values.end())appendLine(output,"NOT_FOUND");else{values.erase(at);appendLine(output,"REMOVED");}}else if(kind==2)query("max_xor",x);else if(kind==3)query("min_xor",x);else{input<<"count "<<x<<'\n';appendLine(output,static_cast<int>(std::count(values.begin(),values.end(),x)));}}return{input.str(),output.str()};}
int occurrences(const std::string& text,const std::string& pattern){int count=0;for(std::size_t i=0;i+pattern.size()<=text.size();++i)if(text.compare(i,pattern.size(),pattern)==0)++count;return count;}
GeneratedCase generateAho(std::mt19937_64& random,int operations){if(operations<4)throw std::runtime_error("A58-aho-corasick-matching operation_limit too small");std::vector<std::string> patterns={"a","aa","he","she","hers"};std::ostringstream input,output;input<<patterns.size()<<' '<<operations<<'\n';for(auto& p:patterns)input<<p<<'\n';auto emit=[&](std::string command,std::string text){input<<command<<' '<<text<<'\n';int total=0,distinct=0;for(auto& p:patterns){int count=occurrences(text,p);total+=count;if(count)++distinct;}appendLine(output,command=="count"?total:distinct);};emit("count","aaaa");emit("distinct","aaaa");emit("count","ushers");emit("distinct","ushers");for(int e=4;e<operations;++e){int length=randomInt(random,1,16);std::string text;for(int i=0;i<length;++i)text+=std::string("ahers")[randomInt(random,0,4)];emit(randomInt(random,0,1)?"count":"distinct",text);}return{input.str(),output.str()};}
std::vector<int> suffixArray(const std::string& text){std::vector<int> sa(text.size());for(int i=0;i<static_cast<int>(text.size());++i)sa[i]=i;std::sort(sa.begin(),sa.end(),[&](int a,int b){return text.substr(a)<text.substr(b);});return sa;}int lcp(const std::string& text,int a,int b){int count=0;while(a+count<static_cast<int>(text.size())&&b+count<static_cast<int>(text.size())&&text[a+count]==text[b+count])++count;return count;}void appendInts(std::ostringstream& output,const std::vector<int>& values){for(std::size_t i=0;i<values.size();++i)output<<(i?" ":"")<<values[i];output<<'\n';}
GeneratedCase generateSuffixArray(std::mt19937_64& random,int operations){if(operations<4)throw std::runtime_error("A59-suffix-array-lcp operation_limit too small");std::string text="mississippi";auto sa=suffixArray(text);std::vector<int> rank(text.size());for(int i=0;i<static_cast<int>(sa.size());++i)rank[sa[i]]=i;std::ostringstream input,output;input<<text<<' '<<operations<<'\n';input<<"suffix_array\n";appendInts(output,sa);input<<"lcp_array\n";std::vector<int> lcps;for(std::size_t i=1;i<sa.size();++i)lcps.push_back(lcp(text,sa[i-1],sa[i]));appendInts(output,lcps);input<<"lcp 1 4\n";appendLine(output,4);input<<"rank 0\n";appendLine(output,rank[0]);for(int e=4;e<operations;++e){int kind=randomInt(random,0,2),a=randomInt(random,0,static_cast<int>(text.size())-1),b=randomInt(random,0,static_cast<int>(text.size())-1);if(kind==0){input<<"rank "<<a<<'\n';appendLine(output,rank[a]);}else if(kind==1){input<<"lcp "<<a<<' '<<b<<'\n';appendLine(output,lcp(text,a,b));}else{int c=randomInt(random,a,static_cast<int>(text.size())-1),d=randomInt(random,b,static_cast<int>(text.size())-1);std::string left=text.substr(a,c-a+1),right=text.substr(b,d-b+1);input<<"compare "<<a<<' '<<c<<' '<<b<<' '<<d<<'\n';appendLine(output,left<right?"<":left>right?">":"=");}}return{input.str(),output.str()};}
long long distinctSubstrings(const std::string& text){std::set<std::string> values;for(std::size_t i=0;i<text.size();++i)for(std::size_t length=1;i+length<=text.size();++length)values.insert(text.substr(i,length));return values.size();}int longestRepeated(const std::string& text){int best=0;for(std::size_t i=0;i<text.size();++i)for(std::size_t j=i+1;j<text.size();++j){int length=0;while(j+length<text.size()&&text[i+length]==text[j+length])++length;best=std::max(best,length);}return best;}
GeneratedCase generateSuffixAutomaton(std::mt19937_64& random,int operations){if(operations<8)throw std::runtime_error("A60-suffix-automaton-index operation_limit too small");std::string text;std::ostringstream input,output;input<<operations<<'\n';auto append=[&](char c){input<<"append "<<c<<'\n';text+=c;};append('a');append('b');append('a');append('b');append('a');input<<"contains aba\n";appendLine(output,"true");input<<"occurrences aba\n";appendLine(output,2);input<<"distinct_substrings\n";appendLine(output,9);for(int e=8;e<operations;++e){int kind=randomInt(random,0,4);if(kind<=1&&text.size()<25)append("abc"[randomInt(random,0,2)]);else if(kind==2){std::string p=kWords[randomInt(random,0,static_cast<int>(kWords.size())-1)];input<<"contains "<<p<<'\n';appendLine(output,text.find(p)==std::string::npos?"false":"true");}else if(kind==3){std::string p(1,"abc"[randomInt(random,0,2)]);input<<"occurrences "<<p<<'\n';appendLine(output,occurrences(text,p));}else if(kind==4){input<<"distinct_substrings\n";appendLine(output,static_cast<int>(distinctSubstrings(text)));}else{input<<"longest_repeated\n";appendLine(output,longestRepeated(text));}}return{input.str(),output.str()};}
} void registerStringIndexGenerators(CaseGeneratorRegistry& registry){registry.emplace("A55-trie-multiset",generateTrie);registry.emplace("A56-radix-tree-dictionary",generateRadix);registry.emplace("A57-xor-trie-multiset",generateXorTrie);registry.emplace("A58-aho-corasick-matching",generateAho);registry.emplace("A59-suffix-array-lcp",generateSuffixArray);registry.emplace("A60-suffix-automaton-index",generateSuffixAutomaton);} }
